name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-south-1 \
            | docker login --username AWS --password-stdin 173554685967.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build and push Admin Service
        run: |
          docker build -t streamingapp-admin:latest ./backend/adminService
          docker tag streamingapp-admin:latest 173554685967.dkr.ecr.ap-south-1.amazonaws.com/streamingapp-admin:latest
          docker push 173554685967.dkr.ecr.ap-south-1.amazonaws.com/streamingapp-admin:latest

      - name: Build and push Auth Service
        run: |
          docker build -t streamingapp-auth:latest ./backend/authService
          docker tag streamingapp-auth:latest 173554685967.dkr.ecr.ap-south-1.amazonaws.com/streamingapp-auth:latest
          docker push 173554685967.dkr.ecr.ap-south-1.amazonaws.com/streamingapp-auth:latest

      - name: Build and push Chat Service
        run: |
          docker build -t streamingapp-chat:latest ./backend/chatService
          docker tag streamingapp-chat:latest 173554685967.dkr.ecr.ap-south-1.amazonaws.com/streamingapp-chat:latest
          docker push 173554685967.dkr.ecr.ap-south-1.amazonaws.com/streamingapp-chat:latest

      - name: Build and push Streaming Service
        run: |
          docker build -t streamingapp-streaming:latest ./backend/streamingService
          docker tag streamingapp-streaming:latest 173554685967.dkr.ecr.ap-south-1.amazonaws.com/streamingapp-streaming:latest
          docker push 173554685967.dkr.ecr.ap-south-1.amazonaws.com/streamingapp-streaming:latest

      - name: Build and push UI Service
        run: |
          docker build -t streamingapp-ui:latest ./frontend
          docker tag streamingapp-ui:latest 173554685967.dkr.ecr.ap-south-1.amazonaws.com/streamingapp-ui:latest
          docker push 173554685967.dkr.ecr.ap-south-1.amazonaws.com/streamingapp-ui:latest
