apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.ui.name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.services.ui.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.services.ui.name }}
    spec:
      containers:
        - name: {{ .Values.services.ui.name }}
          image: "{{ .Values.image.repository }}/{{ .Values.services.ui.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.services.ui.port }}
