apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.admin.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.services.admin.name }}
  ports:
    - port: {{ .Values.services.admin.port }}
      targetPort: {{ .Values.services.admin.port }}
